name: Deploy to GitHub Pages

on: 
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Create config.js from Secret 
        run: |
          echo "export const CEREBRAS_API_KEY = '${{ secrets.CEREBRAS_API_KEY }}';" > config.js
        shell: bash

      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
